### ISSUE TITLE
Why my AES result wrong?

### ISSUE THREAD

**Issue by ankisme** [aykxt/crypto#3]
My typescript AES result is different from golang language, typescript is client language, and golang is my server language.

Then I try some AES website like https://the-x.cn/en-US/cryptography/Aes.aspx, and I found golang AES result is same as the website AES result.

Here is my code.
```typescript
const te = new TextEncoder();
const key = te.encode("1234567899999999");
const data = te.encode("1234");

const iv = new Uint8Array(16)
for (let i = 0; i < key.length; i++) {
	iv[i] = key[i]
}

const cipher = new Cbc(Aes, key, iv, Padding.PKCS7);
const encrypted = cipher.encrypt(data);
const base64 = Base64.encode(encrypted)
```

The typescript AES result = CbV6UFL7HC7H1smYlwliVg==
The golang AES result = S7gxtGIbOdtmzhn4vAW13A==
The website AES result = S7gxtGIbOdtmzhn4vAW13A==

It's so strange and I am checking my code, does my code has any problem?

**Comment by aykxt** [comment]
Hey, sorry for the long delay. I've been really busy and didn't have time to look into this until now. There was a critical bug in the AES algorithm that caused incorrect output. This should be fixed now with 315d4f675f412f56c21950eaade0fb1a12a45632. I will release a new version soon.
